/**
 * Portrait registry for recurring characters.
 *
 * Each entry is keyed by the same `speakerId` used in chapter voice profiles
 * (see content/kn/voices.json). The chapter player looks up the active
 * style (painterly / comic) and renders the matching portrait next to the
 * speaker's dialogue.
 *
 * Generated by scripts/generate_portraits_local.py at /public/portraits/.
 */

export type ArtStyle = "painterly" | "comic";

interface CharacterEntry {
  id: string;
  displayName: string;
}

const CHARACTERS: CharacterEntry[] = [
  { id: "ravi_auto", displayName: "Ravi" },
  { id: "chai_anna", displayName: "Anna" },
  { id: "hotel_clerk", displayName: "Receptionist" },
  { id: "rangaswamy", displayName: "Rangaswamy" },
  { id: "mysuru_uncle", displayName: "Krishnamurthy uncle" },
  { id: "lokesh", displayName: "Lokesh" },
  { id: "vendor_aunty", displayName: "Vendor aunty" },
  { id: "neighbour", displayName: "Padma" },
  { id: "karthik", displayName: "Karthik" },
  { id: "anika", displayName: "Anika" },
  { id: "cook_aunty", displayName: "Saraswati" },
  { id: "pharmacist", displayName: "Pharmacist" },
  { id: "appa", displayName: "Appa" },
  { id: "amma", displayName: "Amma" },
  { id: "temple_auntie", displayName: "Temple auntie" },
  { id: "anika_friend", displayName: "Divya" },
  { id: "mom", displayName: "Amma (mum)" },
];

export function getPortraitSrc(
  speakerId: string,
  style: ArtStyle
): string | null {
  if (!CHARACTERS.some((c) => c.id === speakerId)) return null;
  return `/portraits/${style}/${speakerId}.jpg`;
}

export function getCharacterDisplayName(speakerId: string): string | null {
  return CHARACTERS.find((c) => c.id === speakerId)?.displayName ?? null;
}
